### ISSUE TITLE
Database Connection

### ISSUE THREAD

**Issue by omarmagdy217** [AmrHosam/SE2018G22#4]
### **Which database extension should we use?**

- PDO
- MySQLi

**Comment by omarmagdy217** [comment]
This link may guide us to the perfect choice, so please read it carefully
@omarshafik @omarmohamed77 @SalmaElbehairy 
https://websitebeaver.com/php-pdo-vs-mysqli#code-differences

**Comment by omarshafik** [comment]
I strongly recommend using pdo as it's easier to securely insert into a table.
In order to protect our database from sql injection we must use mysqli_real_escape_string() function when using mysqli, on the other hand pdo handels sql injection with a simple prepare command; for clarification refer to this link [https://stackoverflow.com/questions/14012642/what-is-the-pdo-equivalent-of-function-mysql-real-escape-string](url)

**Comment by omarshafik** [comment]
I have no problem using any, either way I recommend using prepare statements as it's more compact and prevent sql injection.

**Comment by omarmohamed77** [comment]
we can prevent  injections in mysqli using mysql_real_escape_string() function.

**Comment by omarshafik** [comment]
Sure, but this function is redundant, meaning that you will have to use it for all the inserted values while prepared statements aren't.

**Comment by omarmagdy217** [comment]
> Sure, but this function is redundant, meaning that you will have to use it for all the inserted values while prepared statements aren't.

Prepared statements is not dedicated to PDO only, it can be used with either both of them
Check this link: [https://www.w3schools.com/php/php_mysql_prepared_statements.asp](url)
Conclusion: both of MySQLi or PDO will work fine and achieve the same target
